### ISSUE TITLE
Upgrade to node 16

### ISSUE THREAD

**Issue by swananddhole** [ashley-taylor/junit-report-annotations-action#41]
This is throwing the warning for node js version for ubuntu-latest
`Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: aws-actions/configure-aws-credentials, aws-actions/amazon-ecr-login, aws-actions/amazon-ecr-login, aws-actions/configure-aws-credentials`

**Comment by ssbarnea** [comment]
Apparently the marketplace is full of unmaintained actions.
